Repository leviysoft/oolong, pull requests merged in 2023-10, with the labels that each got.

#15 Get rid of strategy matrix
  .github/workflows/ci.yml
Labels: enhancement

#11 Bump scala, add compiler flags
  oolong-bson/src/main/scala/oolong/bson/BsonDecoder.scala
  oolong-bson/src/main/scala/oolong/bson/BsonEncoder.scala
  oolong-bson/src/main/scala/oolong/bson/defaultdec.scala
  oolong-bson/src/test/scala/oolong/bson/derivation/BsonEncoderSpec.scala
  oolong-bson/src/test/scala/oolong/bson/meta/QueryMetaSpec.scala
  oolong-core/src/main/scala/oolong/AstParser.scala
  oolong-core/src/main/scala/oolong/QExpr.scala
  oolong-core/src/main/scala/oolong/UExpr.scala
  oolong-core/src/main/scala/oolong/Utils.scala
  oolong-mongo-it/src/test/scala/oolong/mongo/OolongMongoSpec.scala
  oolong-mongo/src/main/scala/oolong/mongo/BsonUtils.scala
  oolong-mongo/src/main/scala/oolong/mongo/MongoQueryCompiler.scala
  oolong-mongo/src/main/scala/oolong/mongo/MongoQueryNode.scala
  oolong-mongo/src/test/scala/oolong/mongo/QuerySpec.scala
  oolong-mongo/src/test/scala/oolong/mongo/QueryWithMetaSpec.scala
  oolong-mongo/src/test/scala/oolong/mongo/UpdateSpec.scala
  oolong-mongo/src/test/scala/oolong/mongo/UpdateWithMetaSpec.scala
  project/Settings.scala
Labels: chore

#17 Bump library version
  project/Settings.scala
Labels: chore

#18 Add projection docs
  README.md
Labels: documentation

#21 Update release template, bump version
  .github/release-drafter.yml
  project/Settings.scala
Labels: chore

#22 Add option not to print AST during compilation
  .sbtopts
  oolong-mongo/src/main/scala/oolong/mongo/Envs.scala
  oolong-mongo/src/main/scala/oolong/mongo/QueryCompiler.scala
Labels: enhancement

#23 Remove `extends App`
  oolong-mongo/src/main/scala/oolong/mongo/Envs.scala
Labels: chore

#26 Add maven badge to readme
  README.md
Labels: chore

#24 Implement $all
  README.md
  oolong-core/src/main/scala/oolong/AstParser.scala
  oolong-core/src/main/scala/oolong/QExpr.scala
  oolong-mongo/src/main/scala/oolong/mongo/MongoQueryCompiler.scala
  oolong-mongo/src/main/scala/oolong/mongo/MongoQueryNode.scala
  oolong-mongo/src/test/scala/oolong/mongo/QuerySpec.scala
Labels: enhancement

#28 Remove explicit version
  project/Settings.scala
Labels: chore

#27 Add BigDecimal and BigInt support
  oolong-core/src/main/scala/oolong/AstParser.scala
  oolong-mongo/src/test/scala/oolong/mongo/QuerySpec.scala
Labels: enhancement

#31 Use sonatype's badge
  README.md
Labels: chore
